# Generated by Django 3.2.7 on 2021-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disableddays',
            name='is_disbaled',
            field=models.BooleanField(default=False),
        ),
    ]
