# Generated by Django 3.2.7 on 2021-09-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdisableddays',
            name='is_disabled',
        ),
        migrations.AddField(
            model_name='day',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
