# Generated by Django 3.2.7 on 2021-09-14 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_auto_20210913_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewDisabledDays',
        ),
    ]
