# Generated by Django 3.2.7 on 2021-09-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_disableddays_is_disbaled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disableddays',
            old_name='is_disbaled',
            new_name='is_disabled',
        ),
    ]
