# Generated by Django 3.2.7 on 2021-09-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_delete_newdisableddays'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtime',
            name='minutes',
            field=models.IntegerField(default=30),
        ),
    ]
