# Generated by Django 3.2.7 on 2021-09-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0005_alter_disableddays_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddays',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10, null=True),
        ),
    ]
