# Generated by Django 3.2.7 on 2021-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_workingtime_break_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtime',
            name='minutes',
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
