# Generated by Django 3.2.7 on 2021-09-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0006_alter_disableddays_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disableddays',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
