# Generated by Django 3.2.7 on 2021-09-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0010_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
