# Generated by Django 3.2.7 on 2021-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0012_contactusersmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_time',
            field=models.TimeField(default='16:30'),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_time',
            field=models.TimeField(default='08:30'),
        ),
    ]
