# Generated by Django 3.2.7 on 2021-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0013_auto_20211009_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workingtime',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
