# Generated by Django 3.2.7 on 2021-09-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0013_alter_disableddays_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField(default=9)),
                ('minutes', models.IntegerField(default=30)),
                ('end_time', models.IntegerField(default=16)),
            ],
        ),
    ]
