# Generated by Django 3.2.7 on 2021-10-10 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('appointment_date', models.DateField()),
                ('choice', models.CharField(choices=[('A', 'ACCEPT'), ('P', 'PENDING'), ('R', 'REJECTED')], max_length=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_t', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('week_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.day')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsersMessagesToTherapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('appointment_date', models.DateField()),
                ('date_t', models.DateTimeField(null=True)),
                ('choice', models.CharField(choices=[('A', 'ACCEPT'), ('P', 'PENDING'), ('R', 'REJECTED')], max_length=10, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('original_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('week_day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='therapist.day')),
            ],
        ),
    ]
