# Generated by Django 3.2.7 on 2021-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentresponse',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
