# Generated by Django 3.2.7 on 2021-09-05 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_appointment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
