# Generated by Django 3.2.7 on 2021-09-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_appointment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
