# Generated by Django 3.2.7 on 2021-09-05 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_appointment_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('appointment_date', models.DateField()),
                ('choice', models.BooleanField(null=True)),
                ('original_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
            ],
        ),
    ]
