# Generated by Django 3.2.7 on 2021-09-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_appointmentresponse_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentresponse',
            name='choice',
        ),
    ]
