# Generated by Django 3.2.6 on 2021-09-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210905_1806'),
        ('patient', '0008_remove_appointmentresponse_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
