# Generated by Django 3.2.7 on 2021-09-09 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210909_1717'),
        ('patient', '0008_remove_appointmentresponse_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
