# Generated by Django 3.2.7 on 2021-09-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20210910_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='choice',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('P', 'PENDING'), ('R', 'REJECTED')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentresponse',
            name='choice',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('P', 'PENDING'), ('R', 'REJECTED')], max_length=10, null=True),
        ),
    ]
