# Generated by Django 3.2.7 on 2021-09-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_auto_20210911_1743'),
        ('patient', '0011_auto_20210910_1353'),
    ]

    operations = [
    ]
